In [1]:
import pymssql

conn = pymssql.connect(
    server='localhost',
    port=1433,
    user='sa',
    password='YourStrong!Passw0rd',
    database='EcommerceDB'
)

cursor = conn.cursor()

cursor.execute("SELECT name FROM sys.databases")

for row in cursor.fetchall():
    print(row)

('master',)
('tempdb',)
('model',)
('msdb',)
('EcommerceDB',)
('DEPI',)
('DepiRound3',)
('depi_data_engineering',)
('SalesDB',)
('sales',)
('AitroniX',)
('actula_database',)
('orders_datawarehouse',)
('SalesData',)
('sales_datewarehouse',)
('salesdatabase',)
('Sales_data_warehouse',)
('Novus',)
('eraapro',)

In [2]:
cursor = conn.cursor()

cursor.execute("SELECT * from customers")

for row in cursor.fetchall():
    print(row)

(1, 'Ahmed', 'Hassan', 'ahmed.hassan@email.com', '+201001111111', 'M', datetime.date(1995, 3, 15), datetime.datetime(2025, 1, 10, 0, 0), 'Active')
(2, 'Mohamed', 'Ali', 'mohamed.ali@email.com', '+201002222222', 'M', datetime.date(1992, 7, 20), datetime.datetime(2025, 1, 15, 0, 0), 'Active')
(3, 'Sara', 'Mahmoud', 'sara.mahmoud@email.com', '+201003333333', 'F', datetime.date(1998, 2, 11), datetime.datetime(2025, 2, 1, 0, 0), 'Active')
(4, 'Omar', 'Khaled', 'omar.khaled@email.com', '+201004444444', 'M', datetime.date(1997, 11, 5), datetime.datetime(2025, 2, 18, 0, 0), 'Active')
(5, 'Mariam', 'Tarek', 'mariam.tarek@email.com', '+201005555555', 'F', datetime.date(1996, 6, 25), datetime.datetime(2025, 3, 5, 0, 0), 'Active')
(6, 'Youssef', 'Adel', 'youssef.adel@email.com', '+201006666666', 'M', datetime.date(1994, 9, 10), datetime.datetime(2025, 3, 20, 0, 0), 'Active')
(7, 'Nour', 'Ibrahim', 'nour.ibrahim@email.com', '+201007777777', 'F', datetime.date(1999, 12, 1), datetime.datetime(2025, 4, 2, 0, 0), 'Active')
(8, 'Karim', 'Samir', 'karim.samir@email.com', '+201008888888', 'M', datetime.date(1993, 4, 18), datetime.datetime(2025, 4, 15, 0, 0), 'Active')
(9, 'Hana', 'Mostafa', 'hana.mostafa@email.com', '+201009999999', 'F', datetime.date(1997, 8, 22), datetime.datetime(2025, 5, 1, 0, 0), 'Active')
(10, 'Mahmoud', 'Fathy', 'mahmoud.fathy@email.com', '+201010101010', 'M', datetime.date(1991, 1, 30), datetime.datetime(2025, 5, 12, 0, 0), 'Active')
(11, 'Aya', 'Sherif', 'aya.sherif@email.com', '+201011111111', 'F', datetime.date(2000, 5, 14), datetime.datetime(2025, 6, 1, 0, 0), 'Active')
(12, 'Mostafa', 'Nabil', 'mostafa.nabil@email.com', '+201012121212', 'M', datetime.date(1995, 10, 9), datetime.datetime(2025, 6, 20, 0, 0), 'Active')
(13, 'Laila', 'Ayman', 'laila.ayman@email.com', '+201013131313', 'F', datetime.date(1998, 3, 19), datetime.datetime(2025, 7, 1, 0, 0), 'Active')
(14, 'Tamer', 'Wael', 'tamer.wael@email.com', '+201014141414', 'M', datetime.date(1990, 12, 12), datetime.datetime(2025, 7, 15, 0, 0), 'Active')
(15, 'Dina', 'Ashraf', 'dina.ashraf@email.com', '+201015151515', 'F', datetime.date(1996, 11, 27), datetime.datetime(2025, 8, 1, 0, 0), 'Active')

In [4]:
import pandas as pd

In [5]:
query = "SELECT * from customers"

In [7]:
data = pd.read_sql(query,conn)

/var/folders/_r/3sb29fjj12d916yfxyrhd_gc0000gn/T/ipykernel_38447/474327875.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(query,conn)

In [8]:
data

,CustomerID,FirstName,LastName,Email,Phone,Gender,DateOfBirth,RegistrationDate,CustomerStatus
0,1,Ahmed,Hassan,ahmed.hassan@email.com,+201001111111,M,1995-03-15,2025-01-10,Active
1,2,Mohamed,Ali,mohamed.ali@email.com,+201002222222,M,1992-07-20,2025-01-15,Active
2,3,Sara,Mahmoud,sara.mahmoud@email.com,+201003333333,F,1998-02-11,2025-02-01,Active
3,4,Omar,Khaled,omar.khaled@email.com,+201004444444,M,1997-11-05,2025-02-18,Active
4,5,Mariam,Tarek,mariam.tarek@email.com,+201005555555,F,1996-06-25,2025-03-05,Active
5,6,Youssef,Adel,youssef.adel@email.com,+201006666666,M,1994-09-10,2025-03-20,Active
6,7,Nour,Ibrahim,nour.ibrahim@email.com,+201007777777,F,1999-12-01,2025-04-02,Active
7,8,Karim,Samir,karim.samir@email.com,+201008888888,M,1993-04-18,2025-04-15,Active
8,9,Hana,Mostafa,hana.mostafa@email.com,+201009999999,F,1997-08-22,2025-05-01,Active
9,10,Mahmoud,Fathy,mahmoud.fathy@email.com,+201010101010,M,1991-01-30,2025-05-12,Active
10,11,Aya,Sherif,aya.sherif@email.com,+201011111111,F,2000-05-14,2025-06-01,Active
11,12,Mostafa,Nabil,mostafa.nabil@email.com,+201012121212,M,1995-10-09,2025-06-20,Active
12,13,Laila,Ayman,laila.ayman@email.com,+201013131313,F,1998-03-19,2025-07-01,Active
13,14,Tamer,Wael,tamer.wael@email.com,+201014141414,M,1990-12-12,2025-07-15,Active
14,15,Dina,Ashraf,dina.ashraf@email.com,+201015151515,F,1996-11-27,2025-08-01,Active

In [9]:
EcommerceDB = dict()

In [21]:
cursor = conn.cursor()

cursor.execute("SELECT TABLE_NAME  FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_TYPE = 'BASE TABLE';")

for row in cursor.fetchall():
    print(row)

('Employees',)
('Customers',)
('Addresses',)
('Categories',)
('Brands',)
('Suppliers',)
('Products',)
('Warehouses',)
('Inventory',)
('Orders',)
('OrderItems',)
('Payments',)
('Shipments',)
('Returns',)
('Reviews',)
('Coupons',)
('Cart',)
('CartItems',)
('Wishlist',)

In [22]:
cursor = conn.cursor()

cursor.execute("SELECT TABLE_NAME  FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_TYPE = 'BASE TABLE';")

for row in cursor.fetchall():
    print(row[0])

Employees
Customers
Addresses
Categories
Brands
Suppliers
Products
Warehouses
Inventory
Orders
OrderItems
Payments
Shipments
Returns
Reviews
Coupons
Cart
CartItems
Wishlist

In [20]:
cursor = conn.cursor()
cursor.execute("SELECT TABLE_NAME  FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_TYPE = 'BASE TABLE';")

tables_names = [ ]

for row in cursor.fetchall():
    tables_names.append(row[0])

In [14]:
tables_names

['Employees',
 'Customers',
 'Addresses',
 'Categories',
 'Brands',
 'Suppliers',
 'Products',
 'Warehouses',
 'Inventory',
 'Orders',
 'OrderItems',
 'Payments',
 'Shipments',
 'Returns',
 'Reviews',
 'Coupons',
 'Cart',
 'CartItems',
 'Wishlist']

In [15]:
for table in tables_names : 
    query = f"SELECT * from {table}"
    EcommerceDB[table] = pd.read_sql(query, conn )

/var/folders/_r/3sb29fjj12d916yfxyrhd_gc0000gn/T/ipykernel_38447/1454441444.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  EcommerceDB[table] = pd.read_sql(query, conn )

In [19]:
EcommerceDB["Addresses"]

,AddressID,CustomerID,AddressType,Country,City,Street,PostalCode
0,1,1,Shipping,Egypt,Cairo,"Nasr City, Street 10",11765
1,2,1,Billing,Egypt,Cairo,"Nasr City, Street 10",11765
2,3,2,Shipping,Egypt,Giza,"Dokki, Tahrir Street",12611
3,4,2,Billing,Egypt,Giza,"Dokki, Tahrir Street",12611
4,5,3,Shipping,Egypt,Alexandria,"Smouha, Street 5",21615
5,6,3,Billing,Egypt,Alexandria,"Smouha, Street 5",21615
6,7,4,Shipping,Egypt,Cairo,"Maadi, Road 9",11742
7,8,4,Billing,Egypt,Cairo,"Maadi, Road 9",11742
8,9,5,Shipping,Egypt,Giza,"6th October, District 7",12566
9,10,5,Billing,Egypt,Giza,"6th October, District 7",12566
10,11,6,Shipping,Egypt,Cairo,"Heliopolis, El Merghany",11341
11,12,6,Billing,Egypt,Cairo,"Heliopolis, El Merghany",11341
12,13,7,Shipping,Egypt,Mansoura,El Gomhoria Street,35511
13,14,7,Billing,Egypt,Mansoura,El Gomhoria Street,35511
14,15,8,Shipping,Egypt,Cairo,"New Cairo, Fifth Settlement",11835
15,16,8,Billing,Egypt,Cairo,"New Cairo, Fifth Settlement",11835
16,17,9,Shipping,Egypt,Alexandria,"Miami, Khaled Street",21523
17,18,9,Billing,Egypt,Alexandria,"Miami, Khaled Street",21523
18,19,10,Shipping,Egypt,Giza,"Haram, Faisal Street",12555
19,20,10,Billing,Egypt,Giza,"Haram, Faisal Street",12555
20,21,11,Shipping,Egypt,Cairo,"Zamalek, 26th July Street",11211
21,22,11,Billing,Egypt,Cairo,"Zamalek, 26th July Street",11211
22,23,12,Shipping,Egypt,Cairo,Shorouk City,11837
23,24,12,Billing,Egypt,Cairo,Shorouk City,11837
24,25,13,Shipping,Egypt,Giza,Sheikh Zayed,12588
25,26,13,Billing,Egypt,Giza,Sheikh Zayed,12588
26,27,14,Shipping,Egypt,Cairo,Ain Shams,11772
27,28,14,Billing,Egypt,Cairo,Ain Shams,11772
28,29,15,Shipping,Egypt,Alexandria,Stanley,21532
29,30,15,Billing,Egypt,Alexandria,Stanley,21532